<?php

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

/**
 * Table of Contents
 * # INVERVENTION: SCALE IMAGE
 */

namespace App\Http\Controllers;

// easy-peasy documentation writing
// that which this class use-s

use Illuminate\Auth\Events\Registered;
use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Gd\Driver;
use App\Helper\Enumeration\File;
use \App\Rules\FileRule;
use \App\Livewire\UserPicker;
use \Illuminate\Support\Facades\Hash;
use \App\Rules\GroupRule;
use \App\Rules\UserPickerRule;
use \App\Helper\Enumeration\UserFormat;
use App\Helper\ServerDatabaseConversion;
use \App\Helper\Trait\THandleSearchbox;
use \App\Models\Group;
use \App\Models\Role;
use App\Models\User; // User::FindOrFail($user_id)

//-----------------------------------------------------------------------------
class UserController extends Controller
{
  use THandleSearchbox;

  ///////////////////////////////////////////////////////////////////////////////
  // PUBLIC

  //*****************************************************************************

  /**
   * Must but logged in
   * No need for: Authorization Policies
   */
  
  public function __construct()
  {
    $this->middleware('auth');

  }
  
  //*****************************************************************************
  public function create($code)
  {
    // Authorization Policy
    $this->authorize('create', auth()->user());

    $role = Role::all()->where('code', '=', $code)->first();

    $groups = ( $code & config('role.student.code') ) > 0 ? Group::all() : null;

    return view('Access.User.create', [
      'groups' => $groups ?? [],
      'role' => $role,
      // used when adding parent // required: assign student(s)
      'searchboxFormat' => UserFormat::Student
    ]);
  }
  
  //******************************************************************************

  /**
   * protection
   *   view with destroy submission should be protected by Authorization Policies
   *     view with destroy submission has to be generated by admin
   *     admin should have csrf token in his session
   */

  public function destroy(User $user)
  {
    User::destroy($user->id);
    
    return back();

  }

  //*****************************************************************************
  public function edit($user_id)
  {
    $user = User::FindOrFail($user_id);

    $this->authorize('edit', $user);

    return view('Access.User.edit', [
      'user' => $user
    ]);

  }
  
  //*****************************************************************************
  public function index(int $code = 0)
  {
    $data = [];

    $this->authorize('index', auth()->user());

    switch ($code)
    {
      case config('role.null.code') :
      
      // code null

        $data = $this->getRoles();
        break;
      
      default:

        $data = $this->getUsers($code);
        break;
    }
    
    return view('Access.User.index', [
      'data' => $data,
      'code' => $code,
      'search' => $this->getSearch()
    ]);

  }

  //*****************************************************************************
  public function show($user_id)
  {
    $user = User::FindOrFail($user_id);

    $this->authorize('show', $user);

    // this User and Admin can edit
    $canEdit = auth()->user()->can('edit', [User::class, $user]);

    return view('Access.User.show', [
      'canEdit' => $canEdit,
      'user' => $user
    ]);

  }

  //*****************************************************************************
  public function store(int $code)
  {
    $newUserData = $this->getCreateUserData($code);
    
    // dont add one child twice
    $userId = $this->storeNewUser($newUserData, $code);

    return redirect()->route('user.index', ['code' => $code]);
  }

  //*****************************************************************************
  public function update($user_id)
  {
    $user = User::FindOrFail($user_id);
  
    // #1 USE Auth Policy
    // $this->authorize('update', $user);
    
    // #2 SANITIZE User SQL Injection
    // request() = $_POST & $_GET & $_FILE & ...
    $updated = request()->validate([
      'email' 		=> config('validator.email'),
      'another'   => '' // not sanitized
    ]);

    #4 UPDATE Model
    if ($user->update($updated))
    {
      $user->email_verified_at = null;
      $user->save();

      // email has just been updated
      event(new Registered($user));
    }
    

    if ($user->id == auth()->user()->id)
    {
      return redirect()->route('verification.notice');
    }
  
    #5 RETURN Show changes
    return redirect()->route('user.show', ['id' => $user_id]);

  }

  ///////////////////////////////////////////////////////////////////////////////
  // PRIVATE

  //*****************************************************************************
  private function getCreateUserData(int $code)
  {
    // parent requires student(s)
    $users = null;
    if (($code & config('role.parent.code')) > 0)
    {
      $users = request()->validate([
        'usersString' => ['required', 'string', new UserPickerRule()]
      ]);

      $users = $users['usersString'];

      // get unique User Models (students)
      $users = UserPicker::convertToModels($users);
    }

    // student requires group
    $groupId = null;
    if (($code & config('role.student.code')) > 0)
    {
      $groupId = request()->validate([
        // watch out for html input name
        // we dont want it too close to database attribute
        // dangerous
        'group' => ['required', 'regex:/^\d+$/', new GroupRule()]
      ]);

      $groupId = $groupId['group'];
    }

    // email (by default: Laravel should trim and null applicable strings)
    $email = null;
    if (request()->input('email') != null)
    {
      $email = request()->validate([
        'email'         => ['email', 'max:255'],
      ]);

      $email = $email['email'];
    }

    // first-name, last-name, password, image
    $data = request()->validate([
      'firstName'     => ['required', 'string', 'max:255', 'alpha'],
      'lastName'      => ['required', 'string', 'max:255', 'alpha'],
      'password'      => array_merge(config('validator.password'), ['confirmed']),
      'imageFile'     => ['required', 'file', new FileRule(File::PortraitPicture)]
    ]);

    return array_merge(
      $data, [
      'email'   => $email,
      'groupId' => $groupId,
      'users'   => $users
    ]);
  }

  //*****************************************************************************
  private function getUsers(string $code)
  {
    $users = [];
    $links = [];

    $role = Role::where('code', '=' , $code)->get()->first();

    // get users
    $users = $this->handleSearchbox($role->users);

    // sort users by id
    $users = array_sort($users->toArray(), 'id', SORT_ASC);

    // new create sorted links
    foreach ($users as $user)
    {
      $links[] = route('user.show', ['id' => $user['id']]);
    }

    return [
      'users' => $users,
      'links' => $links
    ];
  }

  //*****************************************************************************
  private function getRoles()
  {
    $roles = Role::all();
    $links = [];

    foreach ($roles as $role)
    {
      // translate ...
      $role->name = __(ucfirst($role->name)); 
    }

    // ... and sort by name
    $roles = array_sort($roles->toArray(), 'name', SORT_ASC);

    // now create sorted links
    foreach ($roles as $role)
    {
      $links[] = route('user.index', ['code' => $role['code']]);
    }

    return [
      'roles' => $roles,
      'links' => $links
    ];
  }

  //*****************************************************************************

  /**
   * desc
   *   onSuccess: return userId
   *   onFailure: return -1
   */

  private function storeNewUser(array $data, int $code) : int
  {
    // INVERVENTION: SCALE IMAGE
    $imageMngr = new ImageManager(new Driver());
    // image
    $image = $imageMngr->read($data['imageFile']->path());
    // dimensions
    $width = config('image.portraitPicture.width');
    $height = config('image.portraitPicture.height');
    // dont exceed $width x $height
    $image = $image->scale($width, $height);
    
    // get file name and extensin
    $fileNameExt = ServerDatabaseConversion::getFileName($data['imageFile']);

    // set file relative path
    $relativePath = "/$fileNameExt";
    
    // save
    $image->save(config('fs.path.storage.portraitPicture') . $relativePath);

    // create new User
    $user = new User();
    $user->fill([
      'fname'           => $data['firstName'],
      'lname'           => $data['lastName'],
      'email'           => $data['email'],
      'lastLogIn'       => null,
      'picturePath'     => $relativePath,
      'group_id'        => null,
      // Lookup Role code into id
      'role_id'         => Role::codeToId($code),
      // Hash the password
      'password'        => Hash::make($data['password'])
    ]);

    if (($code & config('role.student.code')) > 0)
    {
      // adding student ...
      $user->group_id = $data['groupId'];
    }

    // save new user in db
    if ( ! $user->save())
    {
      return -1;
    }

    if (($code & config('role.parent.code')) > 0)
    {
      // adding parent ...

      foreach ($data['users'] as $studentWrapper)
      {
        $student = $studentWrapper->first();

        // connect added parent to each student
        $user->children()->attach($student->id);
      }
    }
    
    return $user->id;
  }

}
